# Generated by Django 5.1.1 on 2024-10-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_depth_category_numchild_category_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='category',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='category',
            name='path',
        ),
    ]
